### ISSUE TITLE
Validator.registerAsync not working

### ISSUE THREAD

**Issue by rahul9874563210** [mikeerickson/validatorjs#71]
in the docs 

``` javascript
Validator.registerAsync('username_available', function(username, attribute, req, passes) {
    // do your database/api checks here etc 
    // then call the `passes` method where appropriate: 
    passes(); // if username is available 
    passes(false, 'Username has already been taken.'); // if username is not available 
});
```

i used it like this 

``` javascript
    Validator.registerAsync('exists', function(username, attribute, req, passes) {
        var query = 'SELECT EXISTS (SELECT id FROM ' + table + ' where id=' + value + ') as exist';
        mysqlObj.knex
            .raw(query)
            .then(function (data) {
                if (data[0][0].exist == false) {
                    passes(false, 'id does not exist.'); // if username is not available
                }
            });
    });

var validation = new Validator(initialData, initialRules);
    if (validation.fails()) {
        console.log(validation.errors.all());
        res.status(422).send(validation.errors.all());
    }
    else {

        return next();
    }
```

but the problem is that it always return the error message even if the validation passes.

error is 

``` json
{
  "error": "fails expects a callback when async rules are being tested."
}
```

**Comment by garygreen** [comment]
You need to check if validation passes by a calback when testing async rules. I suspect your doing:

``` javascript
var validator = new Validator(....);
if (validator.fails()) {
    //
}
```

Where it should be:

``` javascript
var validator = new Validator(....);
validator.fails(function() {
    //
});
```

**Comment by rahul9874563210** [comment]
i did that @garygreen .
i hv updated the issue.

**Comment by garygreen** [comment]
Might be related to https://github.com/skaterdav85/validatorjs/commit/84624cb9bcea7b3fe18bba0fe077007624fd94a9

Have you tried master version? There hasn't been a new version with that fix released yet.

**Comment by rahul9874563210** [comment]
i'm using ^2.0.2 version .
@garygreen

**Comment by garygreen** [comment]
Should be fixed in latest.

**Comment by foxhound87** [comment]
Using `registerAsync`, the validation is working but still getting `Unhandled rejection passes expects a callback when async rules are being tested.` using Version 3.6.0

I don't need to pass a callback to  `.passes()` in my case.
